version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.0
  gcp-cli: circleci/gcp-cli@2.1.0
  pulumi: pulumi/pulumi@2.0.0
jobs:
  api_build:
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - restore_cache:
          key: api-dependency-cache-{{ checksum "api/package-lock.json" }}
      - run:
          name: Build
          command: |
            npm install
            npm run build
          working_directory: api
      - save_cache:
          key: api-dependency-cache-{{ checksum "api/package-lock.json" }}
          paths:
            - ./api/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - api/build
  api_test:
    docker:
      - image: circleci/node:14.15.0
      - image: redis:5.0.10
    steps:
      - checkout
      - restore_cache:
          key: api-dependency-cache-{{ checksum "api/package-lock.json" }}
      - run:
          name: Wait for Redis
          command: |
            for i in `seq 1 10`;
            do
            nc -z localhost 6379 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for Redis && exit 1
      - run:
          name: Test
          command: npm run test -- --ci --reporters=default --reporters=jest-junit
          working_directory: api
          environment:
            - JEST_JUNIT_OUTPUT_DIR: ./test-results
            - CONTENTFUL_SPACE_ID: space
            - CONTENTFUL_API_KEY: key
            - JWT_KEY: topsecret
            - REDIS_HOST: 127.0.0.1
            - REDIS_PORT: 6379
      - store_test_results:
          path: ./api/test-results
  api_deploy:
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: Create app.yaml
          command: echo $API_APP_YAML | base64 -d > app.yaml
          working_directory: api/build
      - run:
          name: Deploy
          command: gcloud app deploy
          working_directory: api/build
  app_build:
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - restore_cache:
          key: app-dependency-cache-{{ checksum "app/package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
          working_directory: app
      - save_cache:
          key: app-dependency-cache-{{ checksum "app/package-lock.json" }}
          paths:
            - ./app/node_modules
      - run:
          name: Test
          command: npm run test -- --ci --reporters=default --reporters=jest-junit --runInBand
          working_directory: app
          environment:
            - JEST_JUNIT_OUTPUT_DIR: ./test-results
      - store_test_results:
          path: ./app/test-results
workflows:
  build:
    jobs:
      - api_build
      - api_test:
          requires:
            - api_build
          filters:
            branches:
              ignore: main
      - api_deploy:
          requires:
            - api_build
          context: BUZZQUIZ
          filters:
            branches:
              only:
                - main
      - app_build
