# Usage example:
#
#   docker-compose up
#
version: "3.1"

volumes:
  db:
  redis:

services:
  redis:
    image: redis:5.0.10
    command: redis-server --appendonly yes
    volumes:
    - redis:/data
    ports:
      - "6379:6379"
